
#██████╗░██████╗░░█████╗░███╗░░██╗██╗░░██╗██╗░░██╗
#██╔══██╗██╔══██╗██╔══██╗████╗░██║╚██╗██╔╝╚██╗██╔╝
#██║░░██║██████╔╝███████║██╔██╗██║░╚███╔╝░░╚███╔╝░
#██║░░██║██╔══██╗██╔══██║██║╚████║░██╔██╗░░██╔██╗░
#██████╔╝██║░░██║██║░░██║██║░╚███║██╔╝╚██╗██╔╝╚██╗
#╚═════╝░╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░╚══╝╚═╝░░╚═╝╚═╝░░╚═╝

#this config by dranxX

title: MEMEG